### PR TITLE
feat: update to support laravel-mix@^6

### LINKED ISSUE #20: Laravel Mix 6
I found this error when im using laravel mix 6

TypeError: Cannot add property jigsawDone, object is not extensible

image

### PR DESCRIPTION
**Pull request by owenvoke**
I've been trying to get this working with Laravel Mix 6, however as Mix 6 now uses Webpack 5, it doesn't support extending the `compiler.hooks` object that was added in #14 ([hooks have been frozen as per v5](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#hook-object-frozen)).

I'm not entirely sure how the new `WeakMap` format works, so I haven't been able to implement it. 🤔 Without this, everything appears to work, although obviously the [Minify Jigsaw plugin](https://github.com/thelevicole/webpack-minify-jigsaw-output) won't work. @thelevicole, do you have any idea on how this can be implemented? 🤔

---

EDIT: I've re-added support for the hook in Webpack 4, but trying to work out how to add it for Webpack 5. 🤔

### CODE REVIEW

**Comment by bakerkretzmar** [comment]
@owenvoke thanks a ton for getting this started! I've added a hook using the new `WeakMap` approach based on how https://github.com/jantimon/html-webpack-plugin does it. The build works, but I'm not done testing that Webpack 4 still works or that other plugins like the HTML minification one can actually use the new hook 😅

**Comment by owenvoke** [comment]
Ah, thank you! I just realised how I'd done the `isWebpack4` variable was pretty bad so thanks for updating that too. 👍🏻 This looks great and I'll give it a test too. 😁

**Comment by tpavlek** [comment]
I hope you two don't mind me chiming in to drop an extremely grateful thank you for working on this. It's been very helpful for a project I've been trying to get done over break!

**Comment by bakerkretzmar** [comment]
@tpavlek glad to hear it!

@owenvoke no worries I copied it from `html-webpack-plugin` 😅 

This will definitely need more testing, but I think the new 'right' way for other plugins to access the hook, like the minification one, is this:

```js
const { getJigsawHooks } = require('laravel-mix-jigsaw/hooks');

class MinifyJigsawOutput {
    apply(compiler) {
        compiler.hooks.compilation.tap('MinifyJigsawOutput', (compilation) => {
            getJigsawHooks(compilation).done.tap('MinifyJigsawOutput', () => {
                // plugin stuff
                console.log('Done');
            });
        });
    }
}
```

This seems to be working for me locally.

**Comment by bakerkretzmar** [comment]
Not sure if changing from `done` to `afterEmit` will affect anyone... it's necessary to use a `WeakMap` though because we need the `compilation` object.

**Comment by jasonlbeggs** [comment]
I'm here for this 🙌 

Thanks for working on this guys!

**Comment by owenvoke** [comment]
Well, from my (not so thorough) testing on my site in development, this seems like it works. 🤷🏻 However, I don't use the Minify plugin so haven't tested the hook. I'm going to mark this as ready for review so more people can test. 👍🏻

**Comment by owenvoke** [comment]
I've now tested this with the HTML Minify plugin, and that seems to work as expected with Laravel Mix 6 as well after these changes. 👍🏻

**Comment by bakerkretzmar** [comment]
Thanks again @owenvoke! Will tag a release shortly.

**Pull request merged**
